name: covid19_app
description: Covid 19 infections tracker.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.0
  provider: ^4.3.2+2
  connectivity: ^0.4.9+3

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/flags/United States.png
    - assets/flags/Ethiopia.png
    - assets/flags/Israel.png
    - assets/flags/Kenya.png
    - assets/search.png
    - assets/Default.png
    - assets/empty_watchlist.gif
    - assets/categories/coffee.png
    - assets/categories/nurse.png
    - assets/categories/government.png
    - assets/categories/families.png
    - assets/categories/warehouse.png
